// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVmG3uUle10V5liNJy23LOhr8QglLsx8',
    appId: '1:329717792262:android:dfa5987c0f0f3b4df9cd87',
    messagingSenderId: '329717792262',
    projectId: 'el-ciclista-chapin',
    storageBucket: 'el-ciclista-chapin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4tnmuk_-_DXNjg0rb9dN4zBFLcNutEs',
    appId: '1:329717792262:ios:9d06e3940f15c73bf9cd87',
    messagingSenderId: '329717792262',
    projectId: 'el-ciclista-chapin',
    storageBucket: 'el-ciclista-chapin.firebasestorage.app',
    iosBundleId: 'com.example.elCiclistaChapin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tVsJrUC2IS43EAQcypToPCfk0SBBiQ4',
    appId: '1:329717792262:web:6674dae4ad12e956f9cd87',
    messagingSenderId: '329717792262',
    projectId: 'el-ciclista-chapin',
    authDomain: 'el-ciclista-chapin.firebaseapp.com',
    storageBucket: 'el-ciclista-chapin.firebasestorage.app',
  );

}